### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by MoosGames** [Bowbee/MoveAnything#14]
Hello, could you please add some instructions on how to install this addon-fork to the readme file? I've deleted the original moveanything and after downloading the .zip I placed its contents into the interface/addons folder, but it doesn't appear in the ingame addons list. I'm not used to install addons directly via github, would be nice if I could just use the curseforge addon manager to install this and meanwhile have some instructions on how to manually get this going. Thank you!

**Comment by Voxxel** [comment]
You need to rename the "MoveAnything-master" folder to "MoveAnything" after you copied over from the zip. It's a common stuff to do for github projects.

**Comment by MoosGames** [comment]
> 

Okay, thank you! <3
Works fine now, that was easy. Maybe adding the line "download, unzip and copy into interface/addons then rename to MoveAnything" in the readme would still help anyone unexperienced like me. It's very likely, that more people that usually just install from their addon manager are looking to install this fork manually and may struggle with it.
