### ISSUE TITLE
Some additional fixes

### ISSUE THREAD

**Issue by RMLR-Emil** [Bowbee/MoveAnything#2]
Hi.
Thanks for the fixes.

I got some LUA errors after I installed your version, so I have made the following changes, in to get rid of them:
BlizzardOptions.xml -> line 55: removed self:ApplyBackdrop()
MoveAnything.lua -> line 5217: Fixed typo (MAOptsSquareMM should be MAOptSquareMM)
MoveAnything.lua -> line 5419: Fixed MAOptRowsSlider slider in options. Added the line: _G["MAOptRowsSlider"]:SetValue(num)

Modules\Position.lua -> line 64: removed UIPARENT_MANAGED_FRAME_POSITIONS[v:GetName()]
The updated line is:
if not v.ignoreFramePositionManager and v.GetName and not v.ignoreFramePositionManager and not MovAny:IsModified(v) and v.GetName then

Note: I am usure what UIPARENT_MANAGED_FRAME_POSITIONS do, but it returned nil when using /run, and from what I have been using it for, it didn't break anything or returning errors.

And to get rid of 'out of date':
MoveAnything.toc -> line 1: Updated Interface value to 100000

Fix to move the LFG/LFR/PvP queue button:
FrameList.lua -> line 333: Removed 'Minimap'. Line is now:
API:AddElement({name = "QueueStatusButton", displayName = "Dungeon Status Button"}, c)

To Move the XP/Reputation bar, I've added the following:
FrameList.Lua -> line 311 (just above c = API:GetCategory("Class Specific") ):
API:AddElement({name = "StatusTrackingBarManager", displayName = "XP/Reputation bar"}, c)

Attached are the files I've ended up with.
I'm new to git(hub), so apologies for not using commit etc. to update.

[MoveAnything.lua.txt](https://github.com/Bowbee/MoveAnything/files/9896283/MoveAnything.lua.txt)
[Position.lua.txt](https://github.com/Bowbee/MoveAnything/files/9896284/Position.lua.txt)
[BlizzardOptions.xml.txt](https://github.com/Bowbee/MoveAnything/files/9896285/BlizzardOptions.xml.txt)

**Comment by Hyphie24** [comment]
Can create a fork and generate a Pull request to make it easier to convert

**Comment by Bowbee** [comment]
Hi, I am not maintaining this due to licensing concerns. If you push a modification commenting out code or small fixes, im happy to merge this in.
Git repo will be deleted as soon as main addon is updated for 10.0

**Comment by Voxxel** [comment]
Excuse me, Bowbee but where do you see the main addon is updated? 

I see only a 9.x update as the latest file on :

https://www.curseforge.com/wow/addons/move-anything/files/all

**Comment by Bowbee** [comment]
The main addon hasnt been updated for 10.0 yet, it will show up on curseforge when it is completed by the original author (not me)

**Comment by Voxxel** [comment]
> The main addon hasnt been updated for 10.0 yet, it will show up on curseforge when it is completed by the original author (not me)

Ah, sorry, I've misread it in your last comment. :P
