### ISSUE TITLE
Got this error.

### ISSUE THREAD

**Issue by dfurray** [Bowbee/MoveAnything#3]
Firstly, thank you for this update, you're amazing. 
I have no problems with this not being fixed just sharing as I'm not good enough with LUA to fix this sort of thing yet.

1x Interface/AddOns/MoveAnything/MoveAnything.lua:3074: attempt to index local 'p' (a nil value)
[string "@Interface/AddOns/MoveAnything/MoveAnything.lua"]:3074: in function `MoverUpdatePosition'
[string "@Interface/AddOns/MoveAnything/MoveAnything.lua"]:3901: in function `Nudge'
[string "@Interface/AddOns/MoveAnything/MoveAnything.lua"]:5883: in function <Interface/AddOns/MoveAnything/MoveAnything.lua:5882>

Locals:
self = <table> {
 GroupLayers = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:3027
 UpdateGUI = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:3386
 OnMoveCheck = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:2595
 modules = <table> {
 }
 MAFEFrameAtCursor = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:2284
 CopyProfile = <function> defined @Interface/AddOns/MoveAnything/Profile.lua:147
 _AddNamedChildren = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:4168
 AttachMoverToFrame = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:2388
 hFocusFrame_Update = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:627
 NoReparent = <table> {
 }
 MoverOnSizeChanged = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:3083
 ProfileDropdownOnLoad = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:5343
 Alpha = <table> {
 }
 MoverUpdatePosition = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:3046
 AddModule = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:6439
 rendered = true
 ToggleGUI = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:2587
 SerializeFrame = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:6388
 GroupScale = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:2896
 hStanceBar_UpdateState = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:501
 minimizedMovers = <table> {
 }
 RowTitleClicked = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:3300
 ToggleFrameEditors = <function> defined @Interface/AddOns/MoveAnything/FrameEditor.lua:6
 OnHideCheck = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:2605
 lDisallowedFrames = <table> {
 }
 ResetProfile = <function> defined @Interface/AddOns/MoveAnything/Profile.lua:121
 SyncErrorHandler = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:1330
 hSetPoint = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:1465
 guiLines = 3
 VerifyFrameData = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:1198
 UpdateGUIIfShown = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:3606
 GetBagInContainerFrame = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:4046
 Backdrop = <table> {
 }
 currentMover = MAMover1 {
 }
 SafeHideFrameAtCursor = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:2103
 searchWord = "game"
 Position = <table> {
 }
 _AddDependents = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:4150
 lForceProtected = <table> {
 }
 hSetScale = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:1633
 SyncUIPanels = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:4005
 OnCheckToggleModifiedFramesOnly = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:2859
 SyncAllFrames = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:1262
 AddCore = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:6431
 HookFrame = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:1729
 moverPrefix = "MAMover"
 GrabContainerFrame = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:4058
 DDMStrataList = <table> {
 }
 UnhookTooltip = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:4698
 inited = true
 UnlockParent = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:1546
 lastFrameName = "GameMenuButtonMoveAnything"
 lAllowedMAFrames = <table> {
 }
 TooltipShow = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:4783
 userData = <table> {
 }
 defFrames = <table> {
 }
 HideFrame = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:2630
 ProfileDropDownClicked = <function> defined @Interface/AddOns/MoveAnything/MoveAnything.lua:5350
 lEnableMouse = <table> {
 }
 Dump = <function> defined @Int

**Comment by Bowbee** [comment]
Thank you for the issue request. Sorry, I wont be able to fix this - please see the updated readme on the repo front page. Cheers
