### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Mithras2801** [Bowbee/MoveAnything#4]
https://github.com/Bowbee/MoveAnything/blob/caea9f95de645d750ed085de3eaa6069c1f77133/Modules/Position.lua#L45

Message: Interface/AddOns/MoveAnything/Modules/Position.lua:45: attempt to index global 'UIPARENT_MANAGED_FRAME_POSITIONS' (a nil value)
Time: Tue Nov  1 14:34:05 2022
Count: 9
Stack: Interface/AddOns/MoveAnything/Modules/Position.lua:45: attempt to index global 'UIPARENT_MANAGED_FRAME_POSITIONS' (a nil value)

Locals: <none>

**Comment by Bowbee** [comment]
Please read the readme

**Comment by Mithras2801** [comment]
thx for info
