### ISSUE TITLE
Found some Errors.

### ISSUE THREAD

**Issue by ghost** [Bowbee/MoveAnything#6]
Message: [string "*BlizzardOptions.xml:54_OnLoad"]:1: attempt to call method 'ApplyBackdrop' (a nil value)
Time: Sat Nov  5 19:49:51 2022
Count: 1
Stack: [string "*BlizzardOptions.xml:54_OnLoad"]:1: attempt to call method 'ApplyBackdrop' (a nil value)
[string "*BlizzardOptions.xml:54_OnLoad"]:1: in function <[string "*BlizzardOptions.xml:54_OnLoad"]:1>

Locals: self = MAOptRowsSlider {
 0 = <userdata>
 NineSlice = Frame {
 }
 Thumb = MAOptRowsSliderThumb {
 }
 Text = MAOptRowsSliderText {
 }
 High = MAOptRowsSliderHigh {
 }
 Low = MAOptRowsSliderLow {
 }
}
(*temporary) = nil
(*temporary) = MAOptRowsSlider {
 0 = <userdata>
 NineSlice = Frame {
 }
 Thumb = MAOptRowsSliderThumb {
 }
 Text = MAOptRowsSliderText {
 }
 High = MAOptRowsSliderHigh {
 }
 Low = MAOptRowsSliderLow {
 }
}
(*temporary) = "attempt to call method 'ApplyBackdrop' (a nil value)"

Message: Interface/AddOns/MoveAnything/MoveAnything.lua:5217: attempt to index global 'MAOptsSquareMM' (a nil value)
Time: Sat Nov  5 19:53:41 2022
Count: 2
Stack: Interface/AddOns/MoveAnything/MoveAnything.lua:5217: attempt to index global 'MAOptsSquareMM' (a nil value)
[string "@Interface/AddOns/MoveAnything/MoveAnything.lua"]:5217: in function `OnCommit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:525: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:523>
[string "=[C]"]: in function `xpcall'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:501: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:498>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:509: in function `ForEachCanvas'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:523: in function `CommitCanvases'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:247: in function `Commit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:276: in function `ExitWithCommit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:257: in function `Close'
[string "@Interface/FrameXML/UIParent.lua"]:3984: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals: <none>

**Comment by Bowbee** [comment]
Hey, please read the readme :)

Thank you for the issue request
